### ISSUE TITLE
Please invite me to Codinasion

### ISSUE THREAD

**Issue by kunalnandre** [codinasion/.github#11]
### Name

Kunal Nandre

**Comment by harshraj8843** [comment]
Hey @kunalnandre

Welcome to codinasion :tada:

An invitation has been sent to you to join the organization. Please check your email for the invitation and accept it.

**Comment by kunalnandre** [comment]
i have not received mail for join the Organisation....

**Comment by harshraj8843** [comment]
Hey @kunalnandre 

Thanks for reporting this 👍🏻 

Can you please confirm this issue now (whether you receive the email or not) ?

**Comment by kunalnandre** [comment]
Yes

**Comment by harshraj8843** [comment]
The issue has been fixed :)

Welcome to the community 🤗

**Comment by kunalnandre** [comment]
Great, thanks for letting me know!
