### ISSUE TITLE
Please invite me to Codinasion

### ISSUE THREAD

**Issue by Abhijeetbyte** [codinasion/.github#7]
### Name

Abhijeet Kumar

**Comment by harshraj8843** [comment]
Hey @Abhijeetbyte

Welcome to codinasion :tada:

An invitation has been sent to you to join the organization. Please check your email for the invitation and accept it.

**Comment by harshraj8843** [comment]
Hey @Abhijeetbyte

Welcome to codinasion :tada:

An invitation has been sent to you to join the organization. Please check your email for the invitation and accept it.
