### ISSUE TITLE
Please invite me to Codinasion

### ISSUE THREAD

**Issue by RichardHan0314** [codinasion/.github#88]
### Name

Richard Han

**Comment by RichardHan0314** [comment]
Hello
I am a full stack developer with 7+ years experience of all kinds of modern javascript frameworks.
I like sharing my knowledge and help other people and learn from them.
Thank you,

**Comment by harshraj8843** [comment]
Hey @RichardHan0314

Welcome to codinasion :tada:

An invitation has been sent to you to join the organization. Please check your email for the invitation and accept it.
